# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_plugin 'vagrant-librarian-puppet-plugin'

Vagrant.configure('2') do |config|
  # All Vagrant configuration is done here. The most common configuration
  # options are documented and commented below. For a complete reference,
  # please see the online documentation at vagrantup.com.

  # Every Vagrant virtual environment requires a box to build off of.
  config.vm.box = "percise64"
  config.vm.box_url = "http://dl.dropbox.com/u/1537815/precise64.box"

  config.vm.network :private_network, ip: "192.168.42.4"
  config.ssh.forward_agent = true

  jarvis_dir = File.expand_path(File.dirname(__FILE__) + "/../../")
  config.vm.synced_folder jarvis_dir, "/home/vagrant/jarvis/", :nfs=>true
  config.vm.synced_folder File.expand_path("~"), "/vagrant_home"

  config.vm.provider :virtualbox do |vb|
    vb.customize ["modifyvm", :id, "--name", "jarvis-chrome"]
    vb.customize ["modifyvm", :id, "--memory", "2048"]
    vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
    vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
    vb.customize ["modifyvm", :id, "--natdnspassdomain1", "on"]
  end

  config.vm.provision :puppet do |puppet|
     puppet.manifests_path = "manifests"
     puppet.manifest_file  = "init.pp"
     puppet.module_path = ["manifests/modules", "modules",]
     #puppet.options = ["--debug",]
  end

end
